<?php

namespace ContainerNWFxxhi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYrD_KJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PYrD.KJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PYrD.KJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.YaIpIDy.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\CategoryController::create()', 'getCategoryControllercreateService', true],
            'App\\Controller\\CategoryController::update' => ['privates', '.service_locator.WFtayVO.App\\Controller\\CategoryController::update()', 'getCategoryControllerupdateService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.ybjbtEe.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.aUUiRmt.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.Jzq_mP0.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController::create' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\ProductController::create()', 'getProductControllercreateService', true],
            'App\\Controller\\ProductController::update' => ['privates', '.service_locator.Fchf_jq.App\\Controller\\ProductController::update()', 'getProductControllerupdateService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.fd98T_I.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.YaIpIDy.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\CategoryController::create()', 'getCategoryControllercreateService', true],
            'App\\Controller\\CategoryController:update' => ['privates', '.service_locator.WFtayVO.App\\Controller\\CategoryController::update()', 'getCategoryControllerupdateService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.ybjbtEe.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.aUUiRmt.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.Jzq_mP0.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController:create' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\ProductController::create()', 'getProductControllercreateService', true],
            'App\\Controller\\ProductController:update' => ['privates', '.service_locator.Fchf_jq.App\\Controller\\ProductController::update()', 'getProductControllerupdateService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.fd98T_I.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\CategoryController::update' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::create' => '?',
            'App\\Controller\\ProductController::update' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\CategoryController:update' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:create' => '?',
            'App\\Controller\\ProductController:update' => '?',
            'App\\Controller\\ProductController:delete' => '?',
        ]);
    }
}
