<?php

namespace ContainerNWFxxhi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YaIpIDy.App\Controller\CategoryController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YaIpIDy.App\\Controller\\CategoryController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\CategoryController::index()', $container);
    }
}
