<?php

namespace ContainerNWFxxhi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jzq_mP0.App\Controller\ProductController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jzq_mP0.App\\Controller\\ProductController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.Jzq_mP0.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Jzq_mP0": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'product' => 'App\\Entity\\Product',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ProductController::show()', $container);
    }
}
