<?php

namespace ContainerNWFxxhi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fchf_jq.App\Controller\ProductController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fchf_jq.App\\Controller\\ProductController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.Fchf_jq.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Fchf_jq": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'product' => 'App\\Entity\\Product',
            'entityManager' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ProductController::update()', $container);
    }
}
