<?php

namespace ContainerNWFxxhi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aUUiRmt.App\Controller\ProductController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aUUiRmt.App\\Controller\\ProductController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ProductController::index()', $container);
    }
}
