<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNWFxxhi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNWFxxhi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNWFxxhi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNWFxxhi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNWFxxhi\App_KernelDevDebugContainer([
    'container.build_hash' => 'NWFxxhi',
    'container.build_id' => '774a87f9',
    'container.build_time' => 1731236659,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNWFxxhi');
