<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'product_api_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/api/products']], [], [], []],
    'product_api_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'product_api_create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/api/products']], [], [], []],
    'product_api_update' => [['id'], ['_controller' => 'App\\Controller\\ProductController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'product_api_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'product_api_search_by_id' => [['id'], ['_controller' => 'App\\Controller\\ProductController::findById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products/search']], [], [], []],
    'product_api_search_by_price' => [['price'], ['_controller' => 'App\\Controller\\ProductController::findByPrice'], [], [['variable', '/', '[^/]++', 'price', true], ['text', '/api/products/search/price']], [], [], []],
    'product_api_search_by_description' => [['description'], ['_controller' => 'App\\Controller\\ProductController::findByDescription'], [], [['variable', '/', '[^/]++', 'description', true], ['text', '/api/products/search/description']], [], [], []],
    'product_api_search_price_greater_than' => [['price'], ['_controller' => 'App\\Controller\\ProductController::findByPriceGreaterThan'], [], [['variable', '/', '[^/]++', 'price', true], ['text', '/api/products/search/price-greater-than']], [], [], []],
];
